language: node_js
node_js:
  - "node"
cache: yarn
install:
  - cd front
  - yarn install
script:
  - yarn  build
after_script:
  - git config --global user.email "fwgood@qq.com"
  - git config --global user.name "fwgood"
  - git clone https://$GITHUB_TOKEN@github.com/fwgood/lab-system.git container
  - rm -rf container/docs
  - mv dist container/docs
  - cd container
  - git add .
  - git commit -m 'Travis upate blog'
  - git push -u origin master
branches:
  only:
    - dev
