language: node_js
node_js:
  - "node"
install:
  - cd front
  - npm install
script:
  - npm run build
after_script:
  - git config --global user.email "fwgood@qq.com"
  - git config --global user.name "fwgood"
  - git clone https://$GITHUB_TOKEN@github.com/fwgood/lab-system.git container
  - mv dist container/docs
  - cd container
  - git add .
  - git commit -m 'Travis upate blog'
  - git push -u origin master
branches:
  only:
    - master
